<a href="https://colab.research.google.com/github/Ab-Rouf/Full-NumPy/blob/main/BongoDev(Numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy basic
Numpy=Numerical python

-Numpy is a python Library

-Numpy is used for working with arrays

In [ ]:
import numpy as np

In [ ]:
my_list=[1,2,3,4,5]
print(type(my_list))
print(my_list)

<class 'list'>
[1, 2, 3, 4, 5]


In [ ]:
my_np_array=np.array(my_list)
print(my_np_array)

[1 2 3 4 5]


In [ ]:
my_np_array.dtype

dtype('int64')

In [ ]:
my_np_array.shape

(5,)

In [ ]:
my_np_array.ndim

1

#

In [ ]:
zeros_np_arrays=np.zeros(shape=(3,3))
zeros_np_arrays

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
ones_np_array=np.ones(shape=(10,2), dtype=int)
print(ones_np_array)
print(ones_np_array.dtype)


[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
int64


In [ ]:
# create an array with specific values.

np_arrays=np.full(shape=(2,3),fill_value=15,dtype=int)
print(np_arrays)

[[15 15 15]
 [15 15 15]]


In [ ]:
# create identity matrix
my_matrix=np.eye(4)
print(my_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#type casting in this code
my_matrix_int=my_matrix.astype(int)
print(my_matrix_int)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
sequential_array=np.arange(start=1,stop=10,step=2)
print(sequential_array)

[1 3 5 7 9]


In [ ]:
#create a linearly spaced array
linearly_spaced_array=np.linspace(
    start=1,stop=100,num=7)
print(linearly_spaced_array)


[  1.   17.5  34.   50.5  67.   83.5 100. ]


# Advance Numpy methods

Objectives:

1. Multidimentional Numpy arrays

2. Numpy Operation: indexing, sliacing, reshape, filtering, vectorization, Broadcasting.
3. Numpy Axis
4. Numpy Random

In [ ]:
my_array=np.arange(start=1,stop=10,step=2)
print(my_array)

[1 3 5 7 9]


In [ ]:
#Multidimensional Numpy

scalar=np.array(45)
vector=np.array([1,2,3,4,5,6])
matrix=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,18]])


print(scalar)
print(vector)
print(matrix)


45
[1 2 3 4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 18]]


In [ ]:
# Array slicing
print(vector)
print("after slicing")
print(vector[1:3])
print(vector[1:len(vector):2])

[1 2 3 4 5 6]
after slicing
[2 3]
[2 4 6]


In [ ]:
#slicing with 2d array
print(matrix)
print(matrix[1:3,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 18]]
[[ 6  7]
 [10 11]]


In [ ]:
# again
print(matrix[0:3:2, 0:4:2])

[[ 1  3]
 [ 9 11]]


In [ ]:
# Array reshape

my_2d_array=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(my_2d_array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [ ]:
my_2d_array.shape

(3, 5)

In [ ]:
array_reshape=my_2d_array.reshape(5,3)
print(array_reshape)

print("Again reshape :")
print(array_reshape.reshape(1,3,5))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
Again reshape :
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [ ]:
my_np_array=np.zeros(shape=(3,4,2,2))
print(my_np_array)

[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]]


In [ ]:
rashape_array=my_np_array.reshape(2,2,12)
print(rashape_array)

[[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]


In [ ]:
#Numpy filtering :

Array_filter=np.array([1,2,3,4,5,6])
filter_mask=[True,False,True,False,True,False]

print(Array_filter[filter_mask])


[1 3 5]


In [ ]:
#Numpy vectorizarion

for val in Array_filter:
  if val % 2==1:
    print(val)

Array_filter[Array_filter%2==1]

1
3
5


array([1, 3, 5])

In [ ]:
my_numpy_array=np.array([1,2,3,4,5,6])
print(my_numpy_array)

my_numpy_array+=5

print(my_numpy_array)


[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [ ]:
""" Broadcasting
-converting a lower shape into higher shape for vectorization.


"""
w=np.array([1,2])
x=np.array([[1,2],
            [3,4],
            [7,-8],
            [-5,-3]

            ])
print(w *x)


[[  1   4]
 [  3   8]
 [  7 -16]
 [ -5  -6]]


In [ ]:
print(w.shape)
print(x.shape)

(2,)
(4, 2)


In [ ]:
# Numpy Axis
my_np_array1=np.array(
    [[1,5,-2],
    [0,1,9]]
    )
my_np_array1.shape


(2, 3)

In [ ]:
sum_all_elements=np.sum(my_np_array1)
print(sum_all_elements)

14


In [ ]:
np.sum(my_np_array1,axis=1)

array([ 4, 10])